import type { PublicConversationSignal, PublicConversationScores } from "@church/outreach";

export interface PublicOpportunity extends PublicConversationSignal {
  id: string;
  publishedLabel: string;
  themes: string[];
  scores: PublicConversationScores;
  recommendation: string;
  suggestedActions: string[];
}

export const publicOpportunities: PublicOpportunity[] = [
  {
    id: "opp-001",
    sourceKind: "public_forum",
    sourceLabel: "Synthetic Lowell community forum",
    title: "Looking for a welcoming church with a strong children’s program",
    excerpt:
      "Our family is new to the Lowell area and would appreciate recommendations for a church where parents and children can build community.",
    publicUrl: "https://example.invalid/public-conversation/001",
    publishedAt: "2026-08-07T15:45:00Z",
    publishedLabel: "2 hours ago",
    locality: "Lowell, Massachusetts",
    explicitChurchRequest: true,
    familyRelevance: 98,
    onlineMinistryIntent: 10,
    freshness: 96,
    replyOpportunity: 94,
    contentOpportunity: 91,
    searchOpportunity: 88,
    riskSensitivity: 8,
    themes: ["Lowell", "Families", "Kids ministry", "Community"],
    scores: {
      localRelevance: 100,
      churchIntent: 100,
      familyRelevance: 98,
      onlineMinistryIntent: 10,
      freshness: 96,
      replyOpportunity: 94,
      contentOpportunity: 91,
      searchOpportunity: 88,
      riskSensitivity: 8,
      priority: 94,
    },
    recommendation:
      "A transparent member response could mention Sunday worship, Kids Kingdom, what a first visit is like, and the Plan a Visit page.",
    suggestedActions: [
      "Draft a disclosed member response",
      "Improve the family church landing page",
      "Create a parents FAQ",
      "Track Plan a Visit conversions",
    ],
  },
  {
    id: "opp-002",
    sourceKind: "public_comment",
    sourceLabel: "Synthetic public social discussion",
    title: "Is there an online Bible discussion I can join from home?",
    excerpt:
      "I am not able to attend in person right now but I would like a welcoming Zoom Bible discussion where questions are okay.",
    publicUrl: "https://example.invalid/public-conversation/002",
    publishedAt: "2026-08-07T13:10:00Z",
    publishedLabel: "5 hours ago",
    locality: "Massachusetts",
    explicitChurchRequest: false,
    familyRelevance: 18,
    onlineMinistryIntent: 100,
    freshness: 91,
    replyOpportunity: 90,
    contentOpportunity: 95,
    searchOpportunity: 93,
    riskSensitivity: 12,
    themes: ["Online", "Zoom", "Bible study", "Questions welcome"],
    scores: {
      localRelevance: 72,
      churchIntent: 86,
      familyRelevance: 18,
      onlineMinistryIntent: 100,
      freshness: 91,
      replyOpportunity: 90,
      contentOpportunity: 95,
      searchOpportunity: 93,
      riskSensitivity: 12,
      priority: 89,
    },
    recommendation:
      "Create a clear online Bible study page and invite the person to a voluntary request form rather than asking for private details in public.",
    suggestedActions: [
      "Draft a respectful public reply",
      "Create /online-bible-study",
      "Add time-zone and availability fields",
      "Build a Zoom follow-up workflow",
    ],
  },
  {
    id: "opp-003",
    sourceKind: "public_forum",
    sourceLabel: "Synthetic regional parenting board",
    title: "Church recommendations for teens near Chelmsford or Lowell",
    excerpt:
      "We are looking for a church community where our teenager can form healthy friendships and ask honest faith questions.",
    publicUrl: "https://example.invalid/public-conversation/003",
    publishedAt: "2026-08-06T21:30:00Z",
    publishedLabel: "Yesterday",
    locality: "Chelmsford / Lowell",
    explicitChurchRequest: true,
    familyRelevance: 92,
    onlineMinistryIntent: 15,
    freshness: 82,
    replyOpportunity: 87,
    contentOpportunity: 90,
    searchOpportunity: 84,
    riskSensitivity: 18,
    themes: ["Teens", "Parents", "Chelmsford", "Faith questions"],
    scores: {
      localRelevance: 92,
      churchIntent: 100,
      familyRelevance: 92,
      onlineMinistryIntent: 15,
      freshness: 82,
      replyOpportunity: 87,
      contentOpportunity: 90,
      searchOpportunity: 84,
      riskSensitivity: 18,
      priority: 86,
    },
    recommendation:
      "Answer publicly with accurate teen-ministry information and direct the parent to a guardian-controlled contact form.",
    suggestedActions: [
      "Verify current teen ministry facts",
      "Draft parent-safe response",
      "Improve teen ministry page",
      "Measure contact-form starts",
    ],
  },
  {
    id: "opp-004",
    sourceKind: "public_web",
    sourceLabel: "Synthetic public Q&A page",
    title: "What should I expect at a church service in Lowell?",
    excerpt:
      "I have not attended church in years and would like to know what happens, what to wear, and whether it is okay to come alone.",
    publicUrl: "https://example.invalid/public-conversation/004",
    publishedAt: "2026-08-06T15:00:00Z",
    publishedLabel: "Yesterday",
    locality: "Lowell, Massachusetts",
    explicitChurchRequest: false,
    familyRelevance: 20,
    onlineMinistryIntent: 8,
    freshness: 78,
    replyOpportunity: 82,
    contentOpportunity: 100,
    searchOpportunity: 96,
    riskSensitivity: 9,
    themes: ["First visit", "Come alone", "What to expect", "Lowell"],
    scores: {
      localRelevance: 100,
      churchIntent: 94,
      familyRelevance: 20,
      onlineMinistryIntent: 8,
      freshness: 78,
      replyOpportunity: 82,
      contentOpportunity: 100,
      searchOpportunity: 96,
      riskSensitivity: 9,
      priority: 86,
    },
    recommendation:
      "Strengthen the What to Expect page with plain language, entrance, parking, accessibility, service flow, and an invitation to come without pressure.",
    suggestedActions: [
      "Expand What to Expect",
      "Add first-time visitor FAQ",
      "Create short welcome video",
      "Track directions clicks",
    ],
  },
  {
    id: "opp-005",
    sourceKind: "public_rss",
    sourceLabel: "Synthetic Lowell events feed",
    title: "Community volunteer opportunities this month",
    excerpt:
      "Local residents are asking where families and young adults can serve together during the next few weekends.",
    publicUrl: "https://example.invalid/public-conversation/005",
    publishedAt: "2026-08-05T12:00:00Z",
    publishedLabel: "2 days ago",
    locality: "Lowell, Massachusetts",
    explicitChurchRequest: false,
    familyRelevance: 71,
    onlineMinistryIntent: 0,
    freshness: 69,
    replyOpportunity: 72,
    contentOpportunity: 86,
    searchOpportunity: 70,
    riskSensitivity: 4,
    themes: ["Service", "Families", "Young adults", "Lowell"],
    scores: {
      localRelevance: 100,
      churchIntent: 42,
      familyRelevance: 71,
      onlineMinistryIntent: 0,
      freshness: 69,
      replyOpportunity: 72,
      contentOpportunity: 86,
      searchOpportunity: 70,
      riskSensitivity: 4,
      priority: 72,
    },
    recommendation:
      "Publish genuine, current community-service opportunities and invite voluntary participation without turning service into a membership funnel.",
    suggestedActions: [
      "Verify a real service opportunity",
      "Create public event page",
      "Draft community post",
      "Measure event registrations",
    ],
  },
  {
    id: "opp-006",
    sourceKind: "public_comment",
    sourceLabel: "Synthetic public discussion",
    title: "I want prayer but do not want to post personal details publicly",
    excerpt:
      "Is there a church near Lowell where I can ask for a private conversation without explaining everything online?",
    publicUrl: "https://example.invalid/public-conversation/006",
    publishedAt: "2026-08-07T10:00:00Z",
    publishedLabel: "8 hours ago",
    locality: "Lowell, Massachusetts",
    explicitChurchRequest: true,
    familyRelevance: 5,
    onlineMinistryIntent: 45,
    freshness: 88,
    replyOpportunity: 76,
    contentOpportunity: 84,
    searchOpportunity: 72,
    riskSensitivity: 72,
    themes: ["Prayer", "Privacy", "Conversation", "Lowell"],
    scores: {
      localRelevance: 100,
      churchIntent: 100,
      familyRelevance: 5,
      onlineMinistryIntent: 45,
      freshness: 88,
      replyOpportunity: 76,
      contentOpportunity: 84,
      searchOpportunity: 72,
      riskSensitivity: 72,
      priority: 67,
    },
    recommendation:
      "Do not ask for details publicly. Offer the church’s approved voluntary contact path and include emergency boundaries where appropriate.",
    suggestedActions: [
      "Draft privacy-preserving reply",
      "Review contact-page language",
      "Confirm pastoral routing",
      "Do not create a marketing audience",
    ],
  },
];

export const searchOpportunities = [
  {
    query: "church near me lowell ma",
    intent: "Local visit",
    segment: "local",
    impressions: 860,
    clicks: 31,
    ctr: 3.6,
    position: 9.8,
    trend: 18,
    page: "/church-in-lowell",
    score: 96,
    action: "Improve existing page",
  },
  {
    query: "family church lowell",
    intent: "Families",
    segment: "local",
    impressions: 410,
    clicks: 9,
    ctr: 2.2,
    position: 12.4,
    trend: 26,
    page: "/church-for-families-lowell",
    score: 94,
    action: "Improve family proof and FAQ",
  },
  {
    query: "online bible study massachusetts",
    intent: "Online",
    segment: "online",
    impressions: 690,
    clicks: 4,
    ctr: 0.6,
    position: 18.1,
    trend: 41,
    page: null,
    score: 93,
    action: "Create people-first page",
  },
  {
    query: "zoom bible study",
    intent: "Online",
    segment: "online",
    impressions: 1180,
    clicks: 0,
    ctr: 0,
    position: 0,
    trend: 34,
    page: null,
    score: 92,
    action: "Create online ministry pathway",
  },
  {
    query: "kids ministry lowell",
    intent: "Families",
    segment: "local",
    impressions: 330,
    clicks: 12,
    ctr: 3.6,
    position: 8.7,
    trend: 12,
    page: "/kids-ministry-lowell",
    score: 88,
    action: "Add check-in and safety answers",
  },
  {
    query: "teen church group lowell",
    intent: "Teens",
    segment: "local",
    impressions: 190,
    clicks: 3,
    ctr: 1.6,
    position: 14.2,
    trend: 21,
    page: "/teen-ministry-lowell",
    score: 85,
    action: "Strengthen teen and parent intent",
  },
  {
    query: "what happens at church service",
    intent: "First visit",
    segment: "local",
    impressions: 520,
    clicks: 8,
    ctr: 1.5,
    position: 16.8,
    trend: 9,
    page: "/what-to-expect",
    score: 84,
    action: "Expand practical first-visit detail",
  },
  {
    query: "bible study lowell ma",
    intent: "Bible study",
    segment: "local",
    impressions: 280,
    clicks: 11,
    ctr: 3.9,
    position: 7.9,
    trend: 15,
    page: "/bible-study-lowell",
    score: 82,
    action: "Add availability and next step",
  },
  {
    query: "church community for young adults near me",
    intent: "Young adults",
    segment: "local",
    impressions: 240,
    clicks: 2,
    ctr: 0.8,
    position: 17.5,
    trend: 29,
    page: null,
    score: 81,
    action: "Create substantive ministry page",
  },
  {
    query: "sunday worship lowell",
    intent: "Local visit",
    segment: "local",
    impressions: 170,
    clicks: 18,
    ctr: 10.6,
    position: 4.1,
    trend: 5,
    page: "/sunday-service-lowell",
    score: 72,
    action: "Protect accurate service facts",
  },
] as const;

export const trafficSeries = [
  { label: "Jul 13", visits: 78, conversions: 3 },
  { label: "Jul 16", visits: 92, conversions: 4 },
  { label: "Jul 19", visits: 105, conversions: 6 },
  { label: "Jul 22", visits: 98, conversions: 5 },
  { label: "Jul 25", visits: 132, conversions: 8 },
  { label: "Jul 28", visits: 144, conversions: 9 },
  { label: "Jul 31", visits: 151, conversions: 11 },
  { label: "Aug 3", visits: 173, conversions: 13 },
  { label: "Aug 6", visits: 189, conversions: 16 },
] as const;

export const channelAttribution = [
  { channel: "Google organic", visits: 486, conversions: 31, rate: 6.4 },
  { channel: "Direct / shared link", visits: 248, conversions: 21, rate: 8.5 },
  { channel: "Public social", visits: 174, conversions: 9, rate: 5.2 },
  { channel: "Event pages", visits: 128, conversions: 13, rate: 10.2 },
  { channel: "Online ministry pages", visits: 96, conversions: 12, rate: 12.5 },
  { channel: "Contextual campaigns", visits: 74, conversions: 5, rate: 6.8 },
] as const;

export const localFunnel = [
  { stage: "Search impressions", value: 8240 },
  { stage: "Website visits", value: 1210 },
  { stage: "Plan a Visit opens", value: 184 },
  { stage: "Visit requests", value: 42 },
  { stage: "Visits scheduled", value: 25 },
  { stage: "Synthetic attended", value: 17 },
] as const;

export const onlineFunnel = [
  { stage: "Online page views", value: 740 },
  { stage: "Conversation form opens", value: 132 },
  { stage: "Requests submitted", value: 38 },
  { stage: "Zoom conversations scheduled", value: 24 },
  { stage: "Synthetic attended", value: 18 },
  { stage: "Next step requested", value: 11 },
] as const;

export const contentQueue = [
  {
    id: "draft-1",
    type: "SEO page",
    title: "Online Bible Study in Massachusetts",
    status: "In review",
    owner: "Communications",
    theologicalReview: true,
    updated: "18 minutes ago",
  },
  {
    id: "draft-2",
    type: "Public response",
    title: "Family-friendly church recommendation response",
    status: "Draft",
    owner: "Outreach lead",
    theologicalReview: false,
    updated: "42 minutes ago",
  },
  {
    id: "draft-3",
    type: "Short video",
    title: "What happens on your first Sunday?",
    status: "Approved",
    owner: "Media team",
    theologicalReview: false,
    updated: "Yesterday",
  },
  {
    id: "draft-4",
    type: "Event campaign",
    title: "Lowell community service Saturday",
    status: "Needs facts",
    owner: "Service ministry",
    theologicalReview: false,
    updated: "Yesterday",
  },
] as const;

export const canonicalFacts = [
  {
    label: "Official public name",
    value: "Boston Church Lowell",
    status: "Needs central confirmation",
  },
  { label: "Sunday worship", value: "10:00 AM", status: "Canonical demo fact" },
  { label: "Meeting place", value: "Butler Middle School", status: "Canonical demo fact" },
  {
    label: "Address",
    value: "1140 Gorham Street, Lowell, Massachusetts",
    status: "Canonical demo fact",
  },
  { label: "Member Hub", value: "Invite-only", status: "Configured" },
  { label: "Online ministry", value: "Request-based Zoom conversation", status: "Proposed" },
] as const;

export const localPresenceChecks = [
  {
    label: "Public name approved by central leadership",
    status: "blocked",
    owner: "Central liaison",
  },
  {
    label: "Sunday time consistent across website and structured data",
    status: "ready",
    owner: "Content owner",
  },
  { label: "Rented venue represented accurately", status: "review", owner: "Operations" },
  {
    label: "Parking, entrance, and accessibility instructions verified",
    status: "review",
    owner: "Welcome team",
  },
  {
    label: "Google profile ownership and recovery access documented",
    status: "blocked",
    owner: "Church administrator",
  },
  {
    label: "Online Bible study offer and safeguarding workflow approved",
    status: "planned",
    owner: "Ministry leadership",
  },
] as const;

export const aiVisibilityChecks = [
  {
    prompt: "church near Lowell MA",
    coverage: 78,
    churchMentioned: true,
    factsAccurate: true,
    gap: "Needs stronger family and visitor detail",
  },
  {
    prompt: "family church in Lowell",
    coverage: 46,
    churchMentioned: false,
    factsAccurate: null,
    gap: "Family page lacks authority and corroborating detail",
  },
  {
    prompt: "church with kids program Lowell",
    coverage: 62,
    churchMentioned: true,
    factsAccurate: true,
    gap: "Add ages, check-in, safety, and what parents should expect",
  },
  {
    prompt: "online Bible study Massachusetts",
    coverage: 8,
    churchMentioned: false,
    factsAccurate: null,
    gap: "No approved online-ministry landing page",
  },
  {
    prompt: "teen ministry Lowell",
    coverage: 39,
    churchMentioned: false,
    factsAccurate: null,
    gap: "Strengthen teen and parent information",
  },
  {
    prompt: "Sunday church service Lowell",
    coverage: 84,
    churchMentioned: true,
    factsAccurate: true,
    gap: "Protect canonical schedule data",
  },
] as const;

export const campaigns = [
  {
    id: "camp-1",
    name: "Plan a Visit · Lowell",
    objective: "Sunday visit request",
    geography: "Lowell + approved nearby towns",
    status: "Ready for review",
    channel: "Search",
    spend: "$0 demo",
    conversions: 12,
    guardrail: "Contextual keywords only",
  },
  {
    id: "camp-2",
    name: "Online Bible Conversation",
    objective: "Zoom conversation request",
    geography: "Massachusetts / online",
    status: "Needs ministry approval",
    channel: "Search + social",
    spend: "$0 demo",
    conversions: 8,
    guardrail: "No religious-interest audience lists",
  },
  {
    id: "camp-3",
    name: "What to Expect",
    objective: "First-time visitor education",
    geography: "Organic",
    status: "Content drafting",
    channel: "SEO / AIO",
    spend: "$0",
    conversions: 19,
    guardrail: "People-first page, no doorway duplication",
  },
  {
    id: "camp-4",
    name: "Serve Lowell Together",
    objective: "Public event registration",
    geography: "Lowell",
    status: "Waiting for real event",
    channel: "Community + social",
    spend: "$0",
    conversions: 0,
    guardrail: "Service is not represented as a membership requirement",
  },
] as const;

export const visitorRecords = [
  {
    id: "lead-1",
    displayName: "Synthetic Visitor A",
    pathway: "Plan a Visit",
    source: "Google organic",
    stage: "Visit scheduled",
    consent: "Email",
    owner: "Welcome Team A",
    nextStep: "Send parking and entrance note",
    age: "2 hours",
  },
  {
    id: "lead-2",
    displayName: "Synthetic Visitor B",
    pathway: "Online Bible conversation",
    source: "Online ministry page",
    stage: "Zoom requested",
    consent: "Email",
    owner: "Online Ministry A",
    nextStep: "Offer two approved time windows",
    age: "5 hours",
  },
  {
    id: "lead-3",
    displayName: "Synthetic Household C",
    pathway: "Kids ministry question",
    source: "Family landing page",
    stage: "Conversation established",
    consent: "Email + phone",
    owner: "Welcome Team B",
    nextStep: "Answer guardian-controlled questions",
    age: "Yesterday",
  },
  {
    id: "lead-4",
    displayName: "Synthetic Visitor D",
    pathway: "Bible study",
    source: "Direct shared link",
    stage: "Bible study requested",
    consent: "Email",
    owner: "Study Coordinator",
    nextStep: "Confirm format preference",
    age: "Yesterday",
  },
  {
    id: "lead-5",
    displayName: "Synthetic Visitor E",
    pathway: "Ask a question",
    source: "Public social",
    stage: "New request",
    consent: "Email",
    owner: "Unassigned",
    nextStep: "Assign welcome owner",
    age: "2 days",
  },
] as const;

export const connectorStatuses = [
  {
    name: "Google Search Console",
    kind: "Aggregate search",
    status: "Needs connection",
    lastRun: "Never",
    boundary: "Queries and page metrics; no searcher identity",
  },
  {
    name: "Public website analytics",
    kind: "Traffic and conversion",
    status: "Demo data",
    lastRun: "Synthetic",
    boundary: "Aggregate events only",
  },
  {
    name: "Public forum listening",
    kind: "Public conversations",
    status: "Disabled",
    lastRun: "Never",
    boundary: "Official API or approved public feed only",
  },
  {
    name: "Public RSS / web feeds",
    kind: "Public content",
    status: "Ready for allowlist",
    lastRun: "Never",
    boundary: "No paywalls, private groups, logins, or access controls",
  },
  {
    name: "AI visibility monitor",
    kind: "Answer-engine tests",
    status: "Demo data",
    lastRun: "Synthetic",
    boundary: "Public prompts and public results only",
  },
  {
    name: "Google Business Profile",
    kind: "Local presence",
    status: "Ownership review",
    lastRun: "Never",
    boundary: "Church-owned account and accurate venue representation",
  },
  {
    name: "Zoom",
    kind: "Voluntary online meetings",
    status: "Not connected",
    lastRun: "Never",
    boundary: "Create meetings only after a person requests one",
  },
  {
    name: "Social business accounts",
    kind: "Approved publishing",
    status: "Not connected",
    lastRun: "Never",
    boundary: "Human-approved content; no member-list targeting",
  },
] as const;

export const workerHealth = [
  {
    name: "public-web-listening",
    state: "disabled",
    queue: 0,
    note: "Awaiting approved source adapters",
  },
  {
    name: "search-console-sync",
    state: "configured",
    queue: 0,
    note: "Awaiting credentials and deployed site",
  },
  { name: "seo-intelligence", state: "demo", queue: 4, note: "Synthetic opportunities available" },
  {
    name: "ai-visibility-monitor",
    state: "demo",
    queue: 6,
    note: "Synthetic prompt checks available",
  },
  {
    name: "campaign-intelligence",
    state: "demo",
    queue: 3,
    note: "No budget changes are automated",
  },
  { name: "content-generation", state: "demo", queue: 4, note: "Human approval required" },
] as const;
